# Generated by Django 5.1.5 on 2025-04-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catai', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catimage',
            old_name='uploaded_at',
            new_name='uploadedwhen',
        ),
        migrations.AddField(
            model_name='catimage',
            name='confidence',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='catimage',
            name='facts',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='catimage',
            name='predicted_breed',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
