# Generated by Django 5.1.5 on 2025-05-02 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catai', '0002_rename_uploaded_at_catimage_uploadedwhen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catimage',
            old_name='predicted_breed',
            new_name='predictedbreed1',
        ),
    ]
